http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.url: https://search-phoenix-i43nf624oy3q6kba3zomjljrwq.us-west-2.es.amazonaws.com/
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: changeme

